// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gaitway
{
    internal sealed partial class Vsix
    {
        public const string Id = "Gaitway.790c8307-1b33-4fc9-a73a-c2cf4a911ea0";
        public const string Name = "Gaitway";
        public const string Description = @"Gaitway - Allows for quick navigation between swagger projects.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Adam Giraudet";
        public const string Tags = "";
    }
}
