// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gaitway
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GaitwayString = "9e9f0f0d-bdcf-44e4-b320-4bee44d6d680";
        public static Guid Gaitway = new Guid(GaitwayString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyContextMenuGroup = 0x0002;
        public const int WanderCommand = 0x0100;
    }
}